version: 2.1
jobs:
  build-amd:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=25.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/apache-druid:$TAG .
            # echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            # docker push $DOCKERHUB_USERNAME/circleci-docker-example:$TAG
  build-arm:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=25.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/apache-druid:$TAG .
            # echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            # docker push $DOCKERHUB_USERNAME/circleci-docker-example:$TAG